spring:
  application:
    name: satchiCrmApi
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:postgresql://127.0.0.1:5432/crm?stringtype=unspecified
      #url: jdbc:postgresql://139.198.126.30:5432/crm?stringtype=unspecified
      #url: jdbc:postgresql://erptest.fongwell.com:49131/satchi?stringtype=unspecified
#      username: fongwell
#      password: undead2009

      username: postgres
      password: fongwell

      driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
  transaction:
    rollback-on-commit-failure: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
          dialect: org.hibernate.dialect.PostgreSQL94Dialect
          show_sql: false
          format_sql: false
          user_sql_comments: false
          hbm2ddl-auto: update
server:
  port: 2222
  undertow:
    worker-threads: 3
    io-threads: 10

container:
  brandNews:
    id: -1
    name: brandNewsContainer
  homePage:
    id: -1
    name: homePageContainer
  category:
    id: -1
    name: categoryContainer

topCategory:
  limit: 8

wx:
  defaultClient: test
  appId: test
  appSecret: test
  enabled: true
  jssdk:
    debug: true
  account:
    repository:
      inmemory:
        enabled: true
        accounts:
          test:
            appId: wx6f1303b425b908f2
            appSecret: 8f5ec6918ee9e49bca94c869b8be1da2
            #appId: wxcaf3ca475beb17f7
            #appSecret: be4f2a1424b3bbbff633a1e925078f63
  pay:
    enabled: true
    notifyUrl: http://local.ngrok.fongwell.com/api/wxpay/notify
    account:
      repository:
        inmemory:
          enabled: true
          accounts:
            test:
              appId: wx6f1303b425b908f2
              appSecret: 8f5ec6918ee9e49bca94c869b8be1da2
              mchId: 1501896341
              paySignKey: 1Eg5pmIgfjQE9ypHcYgedSpdA6Bj17UP


qiniu:
  domain: "http://daily.img.fongwell.com/"
  bucket: daily
  key: JtlDTCiRt__r1ZjphswQXo-5uSqMuJGwKnSrDHzg
  secret: gZCi5HYoXuGMRjILUkwrvLsZ9xQa7VOS84a8lw_h
  token:
    timeout: 900
  http:
    maxTotal: 10
    maxPerRoute: 10
